---
title: "main"
author: "Benjamin"
date: '2018-10-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

devtools::load_all()
#devtools::install()

pacman::p_load(dplyr, glue, purrr, stringr, tidyr, jsonlite, rscopus, httr, magrittr)

api_keys <- c("f19f66418460300ea8f6ab71dced56ef", 
              "de161f605b4cddaf6dca837b61e4ae58", 
              "60a5e59310128544264c6b7dd33898ee") # Publication: 19-10
api_key <- api_keys[3]

path <- getwd()
```

```{r}
load("../data/authors.Rdata")
load("../data/author_publications.Rdata")
load("../data/publications.Rdata")

```
+ To do
  * Add renewal for authors list to scrape
  * API Checker + Visualization
  * Updater of authors: to get new publications
  * logger function with safely
  * crayon for colored output

```{r}

add_authors(n_batchs = 100, batch_size = 25, path) # 3000 Authors
for(jj in 1:10){add_publications_authors(n_authors = 100, path)}
for(jj in 1:10){add_abstracts(n_abstracts = 100, path)}
```

```{r}

data_api <- list(author_publications,
     authors,
     publications) %>%
  map(~{.x %>% select(retrieval_time, api_key)}) %>%
  split(c("1","1","2")) %>%
  map(bind_rows)

data_api_authors <- data_api[[1]] %>%
  filter(!duplicated(retrieval_time)) %>%
  mutate(type = "authors")

data_api_entreis <- data_api[[2]] %>%
  filter(!duplicated(retrieval_time)) %>%
  mutate(type = "entries")
```

